sudo: required
dist: trusty
language: python
python:
  - "2.7" # Latest
  - "3.4" # Trusty
  - "3.5" # Xenial
  - "3.6" # Latest
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
install:
- "pip install -r tests/requirements.txt"
script:
- py.test
